---
- name: Check if config.php is present
  ansible.builtin.stat:
    path: /opt/librenms/config.php
  register: __librenms_config

- name: Deploy config.php
  ansible.builtin.template:
    src: opt/librenms/config.php.j2
    dest: /opt/librenms/config.php
    owner: "{{ librenms_user }}"
    group: "{{ librenms_group }}"
    mode: 0640
  notify:
    - restart apache

- name: Deploy librenms cron config.
  ansible.builtin.template:
    src: etc/cron.d/librenms.j2
    dest: /etc/cron.d/librenms
    mode: 0644
  tags:
    - cron
