- name: Install packages
  import_tasks: packages.yml
  tags:
    - packages

- name: Configure user.
  import_tasks: user.yml
  tags:
    - user

- name: Install librenms.
  import_tasks: librenms-install.yml
  tags:
    - librenms-install
    - librenms

- name: Configure librenms.
  import_tasks: librenms-config.yml
  tags:
    - librenms-config
    - librenms