---
- name: Install packages
  ansible.builtin.import_tasks: packages.yml
  tags:
    - packages

- name: Configure user.
  ansible.builtin.import_tasks: user.yml
  tags:
    - user

- name: Install librenms.
  ansible.builtin.import_tasks: librenms-install.yml
  tags:
    - librenms-install
    - librenms

- name: Install nagios plugins.
  ansible.builtin.import_tasks: nagios_plugins.yml
  tags:
    - nagios-plugins
    - nagios

- name: Configure services
  ansible.builtin.import_tasks: services-config.yml
  tags:
    - services

- name: Configure librenms.
  ansible.builtin.import_tasks: librenms-config.yml
  tags:
    - librenms-config
    - librenms
