---
- name: install required packages.
  ansible.builtin.apt:
    name: "{{ librenms_packages }}"
    cache_valid_time: 3600

- name: install rrdcached package.
  ansible.builtin.apt:
    name:
      - rrdcached
    cache_valid_time: 3600
  when:
    -  librenms_rrdcached is defined

- name: install smokeping packages
  ansible.builtin.apt:
    name:
      - smokeping
      - fcgiwrap
    cache_valid_time: 3600
  when: librenms_config_enable_smokeping

- name: install syslog packages
  ansible.builtin.apt:
    name: syslog-ng
    cache_valid_time: 3600
  when: librenms_config_enable_syslog


