- name: Configure php.
  ini_file:
    path: "{{ item }}"
    section: Date
    option: date.timezone
    value: Europe/Berlin
   # state: absent
  with_items: "{{ librenms_php_config_items }}"
  notify: "{{ librenms_php_restart_services }}"