---
- name: Create librenms group.
  ansible.builtin.group:
    name: "librenms"
    state: present

- name: Create librenms user.
  ansible.builtin.user:
    name: librenms
    shell: /bin/bash
    group:
    groups:
      - librenms
    home: /opt/librenms
    create_home: no
    append: no
    system: yes
    state: present
  notify:
    - restart apache

- name: Add www-data to librenms group.
  ansible.builtin.user:
    name: www-data
    groups:
      - www-data
      - librenms
  notify:
    - restart apache
