---
- name: restart nginx
  ansible.builtin.service:
    name: "nginx"
    state: "restarted"

- name: restart php
  ansible.builtin.service:
    name: "php{{ php_version }}-fpm"
    state: "restarted"

- name: restart rrdcached
  ansible.builtin.service:
    name: "rrdcached"
    state: "restarted"

- name: restart snmpd
  ansible.builtin.service:
    name: "snmpd"
    state: "restarted"
